# Generated by Django 5.1.7 on 2025-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
